name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

# this cancels workflows currently in progress if you start a new one
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run Roc tests
    steps:
      - name: Check out roc-url
        uses: actions/checkout@v4
        with:
          path: roc-url

      - name: Install Roc
        uses: hasnep/setup-roc@main
        with:
          roc-version: nightly
          testing: "true"

      - name: Check the Roc version
        run: roc --version

      - name: Run test suite
        working-directory: roc-url
        run: roc test package/main.roc

      - name: Verify docs build
        working-directory: roc-url
        run: roc docs package/main.roc
